#define PGPIO_CLEFT     1 
#define PGPIO_CUP       2 
#define PGPIO_CRIGHT    3 
#define PGPIO_R         4 
#define PGPIO_ZR        5 
#define PGPIO_CDOWN     6 
#define PGPIO_A         7 
#define PGPIO_B         18 
#define PGPIO_DRIGHT    19 
#define PGPIO_DUP       20 
#define PGPIO_DDOWN     21 
#define PGPIO_DLEFT     22 
#define PGPIO_L         23 
#define PGPIO_ZL        28
#define PGPIO_START     29
