#ifndef BOARD_CONFIG_H
#define BOARD_CONFIG_H

#include "driver_define_helper.h"
#include "rgb_define_helper.h"

#define HOJA_BT_LOGGING_DEBUG 0
#define HOJA_WEBUSB_URL     "handheldlegend.github.io/hoja2"

#define HOJA_TRANSPORT_BT_DRIVER        BT_DRIVER_ESP32HOJA
#define HOJA_TRANSPORT_USB_DRIVER       USB_DRIVER_HAL
#define HOJA_TRANSPORT_JOYBUS64_DRIVER  JOYBUS_N64_DRIVER_HAL
#define HOJA_TRANSPORT_JOYBUSGC_DRIVER  JOYBUS_GC_DRIVER_HAL
#define HOJA_TRANSPORT_NESBUS_DRIVER    NESBUS_DRIVER_HAL

#define BLUETOOTH_DRIVER_I2C_INSTANCE   1
#define BLUETOOTH_DRIVER_ENABLE_PIN     26

#define HOJA_USB_MUX_DRIVER         USB_MUX_DRIVER_PI3USB4000A
#define USB_MUX_DRIVER_ENABLE_PIN   24
#define USB_MUX_DRIVER_SELECT_PIN   25

#define HOJA_BATTERY_DRIVER         BATTERY_DRIVER_BQ25180
#define HOJA_IMU_DRIVER             IMU_DRIVER_LSM6DSR
#define ADC_SMOOTHING_STRENGTH      0
#define HOJA_HAPTICS_DRIVER         HAPTICS_DRIVER_ERM_HAL

#define HOJA_RGB_DRIVER             RGB_DRIVER_HAL
#define RGB_DRIVER_LED_COUNT        32
#define RGB_DRIVER_ORDER            RGB_ORDER_GRB
#define RGB_DRIVER_REFRESHRATE      90

#endif
